concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Shared Shell Runner"
  url = "https://gitlab.akarpovich.online/"
  id = 1
  token = "kZqWRSbxGtqoU7AzeN4Q"
  token_obtained_at = 2022-10-20T21:20:56Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]

