concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Shared Shell Runner"
  url = "https://gitlab.akarpovich.online"
  id = 1
  token = "gxs21gnsr8CqS1CafqxB"
  token_obtained_at = 2022-09-06T06:40:14Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]

[[runners]]
  name = "Shared Docker Runner"
  url = "https://gitlab.akarpovich.online"
  id = 2
  token = "gxs21gnsr8CqS1CafqxB"
  token_obtained_at = 2022-09-07T04:31:53Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "alpine"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
