version: "3.6"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    volumes:
      - $GITLAB_HOME/data:/var/opt/gitlab
      - $GITLAB_HOME/logs:/var/log/gitlab
      - $GITLAB_HOME/config:/etc/gitlab
    shm_size: '256m'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        letsencrypt['enable'] = true
        external_url 'https://gitlab.akarpovich.online'
        
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    volumes:
      - ./config.toml:/etc/gitlab-runner/config.toml
    deploy:
      mode: replicated
