version: "3.6"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    volumes:
      - $GITLAB_HOME/data:/var/opt/gitlab
      - $GITLAB_HOME/logs:/var/log/gitlab
      - $GITLAB_HOME/config:/etc/gitlab
    shm_size: '256m'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'email-smtp.us-west-2.amazonaws.com'
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = File.read('/run/secrets/ses_user_name').gsub("\n", "")
        gitlab_rails['smtp_password'] = File.read('/run/secrets/ses_password').gsub("\n", "")
        gitlab_rails['smtp_domain'] = 'akarpovich.online'
        gitlab_rails['smtp_authentication'] = 'login'
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['gitlab_root_email'] = 'admin@akarpovich.online'
        gitlab_rails['initial_root_password'] = File.read('/run/secrets/gitlab_root_password').gsub("\n", "")
        # HTTPS Setup
        letsencrypt['enable'] = true
        external_url 'https://gitlab.akarpovich.online'
    secrets:
      - gitlab_root_password
      - ses_user_name
      - ses_password
        
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    volumes:
      - ./config.toml:/etc/gitlab-runner/config.toml  
    deploy:
      mode: replicated
      replicas: 1
      
configs:
  gitlab:
    file: ./gitlab.rb

secrets:
  gitlab_root_password:
    external: true
  ses_user_name:
    external: true
  ses_password:
    external: true
